### ISSUE TITLE
Plugin is not working when I am trying to use it on  multiple charts present in different cshtml files

### ISSUE THREAD

**Issue by harmanBaincha** [AbelHeinsbroek/chartjs-plugin-crosshair#93]

**Comment by harmanBaincha** [comment]
I am getting following error
TypeError: Cannot read properties of undefined (reading 'dragStarted')
    at Object.beforeTooltipDraw (https://cdn.jsdelivr.net/npm/chartjs-plugin-crosshair@1.2.0:7:4510)
    at Q (https://cdn.jsdelivr.net/npm/chart.js:13:7902)
    at Vs._notify (https://cdn.jsdelivr.net/npm/chart.js:13:84568)
    at Vs.notify (https://cdn.jsdelivr.net/npm/chart.js:13:84394)
    at hn.notifyPlugins (https://cdn.jsdelivr.net/npm/chart.js:13:102246)
    at Object.afterDraw (https://cdn.jsdelivr.net/npm/chart.js:13:166472)
    at Q (https://cdn.jsdelivr.net/npm/chart.js:13:7902)
    at Vs._notify (https://cdn.jsdelivr.net/npm/chart.js:13:84568)
    at Vs.notify (https://cdn.jsdelivr.net/npm/chart.js:13:84394)
    at hn.notifyPlugins (https://cdn.jsdelivr.net/npm/chart.js:13:102246)
TypeError: Cannot read properties of undefined (reading 'length')
    at Object.afterEvent (https://cdn.jsdelivr.net/npm/chartjs-plugin-crosshair@1.2.0:7:2944)
    at Q (https://cdn.jsdelivr.net/npm/chart.js:13:7902)
    at Vs._notify (https://cdn.jsdelivr.net/npm/chart.js:13:84568)
    at Vs.notify (https://cdn.jsdelivr.net/npm/chart.js:13:84394)
    at hn.notifyPlugins (https://cdn.jsdelivr.net/npm/chart.js:13:102246)
    at hn._eventHandler (https://cdn.jsdelivr.net/npm/chart.js:13:102768)
    at s (https://cdn.jsdelivr.net/npm/chart.js:13:100802)
    at hn.e (https://cdn.jsdelivr.net/npm/chart.js:13:43378)
    at https://cdn.jsdelivr.net/npm/chart.js:7:462

**Comment by widjuu** [comment]
@harmanBaincha see https://github.com/AbelHeinsbroek/chartjs-plugin-crosshair/issues/87#issue-1032898332

**Comment by geriatricdan** [comment]
Has anyone addressed this issue?
